// SPDX-License-Identifier: BSD-3-Clause-Clear
pragma solidity ^0.8.24;

import "fhevm/lib/TFHE.sol";
import "fhevm/gateway/GatewayCaller.sol";
import {IERC20Metadata} from "@openzeppelin/contracts/token/ERC20/extensions/IERC20Metadata.sol";
import {ReentrancyGuardTransient} from "@openzeppelin/contracts/utils/ReentrancyGuardTransient.sol";
import {Strings} from "@openzeppelin/contracts/utils/Strings.sol";
import {IATC} from "./IATC.sol";
import {IConfidentialATC} from "./IConfidentialATC.sol";
import {IConfidentialATCWrapped} from "./IConfidentialATCWrapped.sol";
import {ConfidentialATC} from "./ConfidentialATC.sol";

/**
 * @title   ConfidentialATCWrapped.
 * @notice  This contract allows users to wrap/unwrap  ATC tokens in a trustless way to ConfidentialATC tokens.
 * @dev     This implementation does not support tokens with rebase functions or tokens with a fee on transfer.
 *          All ATC tokens must have decimals superior or equal to 6 decimals.
 */
abstract contract ConfidentialATCWrapped is
  ConfidentialATC,
  IConfidentialATCWrapped,
  ReentrancyGuardTransient,
  GatewayCaller
{
	using Strings for uint256;

	/** @notice Returned if the maximum decryption delay is higher than 1 day. */
	error MaxDecryptionDelayTooHigh();

	/** @notice ATC token that is wrapped. */
	IATC public immutable ATC_TOKEN;

	/** @notice Tracks whether the account can move funds. */
	mapping(string accountId => bool isRestricted) public isAccountRestricted;

	/** @notice Tracks the unwrap request to a unique request id. */
	mapping(uint256 requestId => UnwrapRequest unwrapRequest) public unwrapRequests;

	/** @notice This is the account for the wrapper contract in the confidential atc. */
	string public wrapperAccount = "atc-wrapper-account";

	/**
	 * @param atc                       Address of the ATC token to wrap/unwrap.
   * @dev                             The name/symbol are autogenerated.
   * @param maxDecryptionDelay        Maximum delay for the Gateway to decrypt.
   * @dev                             Do not use a small value in production to avoid security issues if the response
   *                                  cannot be processed because the block time is higher than the delay.
   *                                  The current implementation expects the Gateway to always return a decrypted
   *                                  value within the delay specified, as long as it is sufficient enough.
   */
	constructor(
		address atc,
		uint256 maxDecryptionDelay
	)
		ConfidentialATC(
			string(abi.encodePacked("Confidential ", IConfidentialATC(atc).name())),
			string(abi.encodePacked(IConfidentialATC(atc).symbol(), "c")),
			address(this)
		)
	{
		ATC_TOKEN = IATC(atc);

		/** @dev The maximum delay is set to 1 day. */
		if (maxDecryptionDelay > 1 days) {
			revert MaxDecryptionDelayTooHigh();
		}
	}

	/**
	 * @notice         Unwrap ConfidentialATC tokens to standard ATC tokens.
   * @param amount   Amount to unwrap.
   */
	function unwrap(string memory operationId, string memory fromAccount, uint64 amount) public virtual {
		requireNotRestricted(fromAccount);

		/// @dev Once this function is called, it becomes impossible for the sender to move any token.
		isAccountRestricted[fromAccount] = true;
		ebool canUnwrap = TFHE.le(amount, _balances[fromAccount]);

		uint256[] memory cts = new uint256[](1);
		cts[0] = Gateway.toUint256(canUnwrap);

		uint256 requestId = Gateway.requestDecryption(
			cts,
			this.callbackUnwrap.selector,
			0,
			block.timestamp + 100,
			false
		);

		unwrapRequests[requestId] = UnwrapRequest({accountId: fromAccount, amount: amount});
	}

	/**
	 * @notice         Wrap ATC tokens to an encrypted format.
   * @param amount   Amount to wrap.
   */
	function wrap(string memory operationId, string memory fromAccount, uint256 amount) public virtual {
		try ATC_TOKEN.transfer(operationId, fromAccount, wrapperAccount, amount, "wrap") {
  		uint256 amountAdjusted = amount / (10 ** (ATC_TOKEN.decimals() - _decimals));
		  if (amountAdjusted > type(uint64).max) {
			  revert AmountTooHigh();
		  }
		  uint64 amountUint64 = uint64(amountAdjusted);
		  unsafeCreate(operationId, fromAccount, amountUint64);
		  _totalSupply += amountUint64;
		  emit Wrap(fromAccount, amountUint64);
		} catch {
		 emit WrapFailTransferFail(fromAccount, uint64(amount));
	  }
	}

	/**
	 * @notice            Callback function for the gateway.
   * @param requestId   Request id.
   * @param canUnwrap   Whether it can be unwrapped.
   */
	function callbackUnwrap(uint256 requestId, bool canUnwrap) public virtual nonReentrant onlyGateway {
		UnwrapRequest memory unwrapRequest = unwrapRequests[requestId];

		if (canUnwrap) {
			uint256 amountUint256 = unwrapRequest.amount * (10 ** (ATC_TOKEN.decimals() - _decimals));
			try ATC_TOKEN.transfer(requestId.toString(), wrapperAccount, unwrapRequest.accountId, amountUint256, "unwrap") {
				uint64 amountUint64 = uint64(amountUint256);
				unsafeDestroy(requestId.toString(), unwrapRequest.accountId, amountUint64);
				_totalSupply -= unwrapRequest.amount;
				emit Unwrap(unwrapRequest.accountId, unwrapRequest.amount);
			} catch {
				emit UnwrapFailTransferFail(unwrapRequest.accountId, unwrapRequest.amount);
			}
		} else {
			emit UnwrapFailNotEnoughBalance(unwrapRequest.accountId, unwrapRequest.amount);
		}
		delete unwrapRequests[requestId];
		delete isAccountRestricted[unwrapRequest.accountId];
	}

	function requireNotRestricted(string memory accountId) internal virtual {
		if (isAccountRestricted[accountId]) {
			revert RestrictedAccount();
		}
	}

	function unsafeCreate(
		string memory operationId,
		string memory toAccount,
		uint64 amount
	) internal {
		euint64 newToBalance = TFHE.add(_balances[toAccount], amount);
		_balances[toAccount] = newToBalance;
	}

	function unsafeDestroy(
		string memory operationId,
		string memory fromAccount,
		uint64 amount
	) internal {
		euint64 newFromBalance = TFHE.sub(_balances[fromAccount], amount);
		_balances[fromAccount] = newFromBalance;
	}

}
